# Generated by Django 4.2.1 on 2023-05-09 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=100, unique=True)),
                ('evolves_from_species', models.URLField(null=True)),
                ('evolution_chain', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_name', models.CharField(max_length=100, unique=True)),
                ('base_experience', models.CharField(max_length=5, null=True)),
                ('pokemon_sprite', models.URLField(null=True)),
                ('pokemon_height', models.IntegerField()),
                ('pokemon_weight', models.IntegerField()),
                ('pokemon_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='pokemons.species')),
                ('pokemon_type', models.ManyToManyField(to='pokemons.type')),
            ],
        ),
    ]
