# Generated by Django 4.2.1 on 2023-05-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='evolves_from_species',
        ),
    ]
